# Generated by Django 5.1.4 on 2025-03-02 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetabling.instructor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_slot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
