# Generated by Django 5.1.4 on 2025-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0002_instructor_room_year_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
