# Generated by Django 5.1.4 on 2025-03-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0002_alter_room_lecturer_alter_room_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetabling.instructor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
