# Generated by Django 5.1.4 on 2025-03-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0003_alter_room_lecturer_alter_room_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
