# Generated by Django 5.1.6 on 2025-03-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0005_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.department')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.school')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.unit')),
            ],
        ),
    ]
