# Generated by Django 5.1.4 on 2025-03-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0006_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.academicyear'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetabling.year'),
        ),
    ]
